@startuml
actor "Entrepôt de données de santé" as EDS
actor "Producteur de données" as PD

EDS -> PD: <color:blue>Flux 1.1</color> GET [Resource]
PD --> EDS: <color:blue>Flux 1.2</color> 200 OK Bundle Searchset
EDS -> EDS: Ajouter les données reçues aux données existantes

@enduml


