@startuml

scale 300 width

map "**Composant : OncoFAIRMedication**" as Composant #back:TECHNOLOGY;header:LimeGreen {
    codeComposant => code
    typeComposant => <&plus> oncofair-medication-type
}


@enduml