@startuml
set namespaceSeparator ?
hide circle
hide class fields

package IG #DDDDDD{

     package Profiles #DDDDDD{

        class OncoFAIRCarePlan{

             CarePlan.extension => [1..None]
             CarePlan.extension:oncofair-cp-treatment => <&plus>[1..1]
             CarePlan.extension:oncofair-pharmacist-advice => <&plus>[0..1]
             CarePlan.identifier => [1..1]
             CarePlan.status => [None..None]
             CarePlan.title => [1..None]
             CarePlan.note => [None..None]
             CarePlan.note:indication => [0..1]
             CarePlan.note:indication.id => [1..None]
             CarePlan.note:comment => [0..1]
             CarePlan.note:comment.id => [1..None]
        } 

        class OncoFAIREncounter{

             Encounter.identifier => [1..1]
             Encounter.identifier.value => [1..None]
             Encounter.subject => [1..None]
        } 

        class OncoFAIRMedication{

             Medication.extension => [1..None]
             Medication.extension:oncofair-medication-type => <&plus>[1..1]
             Medication.code => [1..None]
        } 

        class OncoFAIRMedicationAdministrationComponent{

             MedicationAdministration.partOf => [1..1]
             MedicationAdministration.category => [1..1]
             MedicationAdministration.medication => [None..None]
             MedicationAdministration.note => [None..None]
             MedicationAdministration.note:description => [0..1]
             MedicationAdministration.note:description.id => [1..None]
             MedicationAdministration.note:comment => [0..1]
             MedicationAdministration.note:comment.id => [1..None]
             MedicationAdministration.note:indication => [0..1]
             MedicationAdministration.note:indication.id => [1..None]
             MedicationAdministration.dosage => [1..None]
             MedicationAdministration.dosage.dose => [1..None]
        } 

        class OncoFAIRMedicationAdministrationElement{

             MedicationAdministration.extension => [1..None]
             MedicationAdministration.extension:oncofair-ma-element-urgent => <&plus>[0..1]
             MedicationAdministration.extension:oncofair-ma-element-expirationdate => <&plus>[0..1]
             MedicationAdministration.extension:oncofair-ma-element-traceability => <&plus>[0..1]
             MedicationAdministration.extension:oncofair-ma-plannedperiod => <&plus>[1..1]
             MedicationAdministration.identifier => [None..None]
             MedicationAdministration.identifier.value => [None..None]
             MedicationAdministration.partOf => [1..1]
             MedicationAdministration.category => [None..None]
             MedicationAdministration.category:code => [0..1]
             MedicationAdministration.category:form => [0..1]
             MedicationAdministration.category:nature => [0..1]
             MedicationAdministration.occurence[x] => [None..None]
             MedicationAdministration.occurence[x]:occurencePeriod => [0..1]
             MedicationAdministration.occurence[x]:occurencePeriod.start => [1..None]
             MedicationAdministration.occurence[x]:occurencePeriod.end => [None..None]
             MedicationAdministration.request => [None..None]
             MedicationAdministration.device => [None..None]
             MedicationAdministration.note => [1..None]
             MedicationAdministration.note:description => [1..1]
             MedicationAdministration.note:description.id => [1..None]
             MedicationAdministration.note:comment => [0..1]
             MedicationAdministration.note:comment.id => [1..None]
             MedicationAdministration.dosage => [None..None]
             MedicationAdministration.dosage.site => [None..None]
             MedicationAdministration.dosage.route => [None..None]
             MedicationAdministration.dosage.method => [None..None]
        } 

        class OncoFAIRMedicationAdministrationReport{

             MedicationAdministration.identifier => [None..None]
             MedicationAdministration.encounter => [1..None]
             MedicationAdministration.performer => [1..1]
             MedicationAdministration.performer.actor => [None..None]
        } 

        class OncoFAIRMedicationRequestPrescription{

             MedicationRequest.extension => [1..None]
             MedicationRequest.extension:oncofair-mr-prescription-validation-date => <&plus>[1..1]
             MedicationRequest.identifier => [1..1]
             MedicationRequest.identifier.value => [1..None]
             MedicationRequest.basedOn => [None..None]
             MedicationRequest.medication => [None..None]
             MedicationRequest.medication.concept.coding.code => [None..None]
             MedicationRequest.encounter => [1..None]
             MedicationRequest.supportingInformation => [None..None]
             MedicationRequest.supportingInformation:accomodationUnit => [0..1]
             MedicationRequest.supportingInformation:accomodationUnit.id => [1..None]
             MedicationRequest.supportingInformation:medicalLiabiltyUnit => [0..1]
             MedicationRequest.supportingInformation:medicalLiabiltyUnit.id => [1..None]
             MedicationRequest.reason => [None..None]
             MedicationRequest.note => [None..1]
        } 

        class OncoFAIRObservation{

             Observation.code => [None..None]
             Observation.effective[x] => [1..None]
             Observation.effective[x]:effectiveDateTime => [1..1]
             Observation.issued => [None..None]
             Observation.value[x] => [1..None]
        } 

        class OncoFAIRPatient{

             Patient.identifier => [1..1]
        } 

        class OncoFAIRMedicationRequestComponent{

             MedicationRequest.extension => [None..None]
             MedicationRequest.extension:oncofair-mr-component-exoneratingald => <&plus>[0..1]
             MedicationRequest.extension:oncofair-mr-component-solute => <&plus>[0..1]
             MedicationRequest.basedOn => [1..1]
             MedicationRequest.medication => [None..None]
             MedicationRequest.note => [1..None]
             MedicationRequest.note:description => [1..1]
             MedicationRequest.note:description.id => [1..None]
             MedicationRequest.note:comment => [0..1]
             MedicationRequest.note:comment.id => [1..None]
             MedicationRequest.note:indication => [0..1]
             MedicationRequest.note:indication.id => [1..None]
             MedicationRequest.dosageInstruction => [None..1]
             MedicationRequest.dosageInstruction.doseAndRate => [None..1]
             MedicationRequest.dosageInstruction.doseAndRate.dose[x] => [1..None]
             MedicationRequest.dosageInstruction.doseAndRate.dose[x]:doseQuantity => [1..1]
             MedicationRequest.substitution => [None..None]
             MedicationRequest.substitution.allowed[x] => [None..None]
             MedicationRequest.substitution.allowed[x]:allowedBoolean => [0..1]
        } 

        class OncoFAIRMedicationRequestElement{

             MedicationRequest.extension => [None..None]
             MedicationRequest.extension:oncofair-element-form => <&plus>[0..1]
             MedicationRequest.extension:oncofair-mr-element-supply => <&plus>[0..1]
             MedicationRequest.extension:oncofair-mr-element-rank => <&plus>[0..1]
             MedicationRequest.extension:oncofair-mr-element-go-nogo => <&plus>[0..1]
             MedicationRequest.extension:oncofair-pharmacist-advice => <&plus>[0..1]
             MedicationRequest.identifier => [1..1]
             MedicationRequest.identifier.value => [1..None]
             MedicationRequest.basedOn => [1..None]
             MedicationRequest.basedOn:prescription => [1..1]
             MedicationRequest.basedOn:element => [0..*]
             MedicationRequest.basedOn:element.extension => [2..None]
             MedicationRequest.basedOn:element.extension:oncofair-mr-element-link-type => <&plus>[1..1]
             MedicationRequest.basedOn:element.extension:oncofair-mr-id-linked-item => <&plus>[1..1]
             MedicationRequest.basedOn:protocol => [0..1]
             MedicationRequest.groupIdentifier => [1..None]
             MedicationRequest.groupIdentifier.value => [1..None]
             MedicationRequest.status => [None..None]
             MedicationRequest.priority => [None..None]
             MedicationRequest.medication => [None..None]
             MedicationRequest.medication.concept.coding.code => [None..None]
             MedicationRequest.requester => [None..None]
             MedicationRequest.device => [None..None]
             MedicationRequest.note => [None..None]
             MedicationRequest.note:wording => [0..1]
             MedicationRequest.note:wording.id => [1..None]
             MedicationRequest.note:indication => [0..1]
             MedicationRequest.note:indication.id => [1..None]
             MedicationRequest.note:comments => [0..1]
             MedicationRequest.note:comments.id => [1..None]
             MedicationRequest.effectiveDosePeriod => [None..None]
             MedicationRequest.effectiveDosePeriod.start => [None..None]
             MedicationRequest.effectiveDosePeriod.end => [None..None]
             MedicationRequest.dosageInstruction => [None..None]
             MedicationRequest.dosageInstruction:element => [0..1]
             MedicationRequest.dosageInstruction:element.id => [1..None]
             MedicationRequest.dosageInstruction:element.text => [None..None]
             MedicationRequest.dosageInstruction:element.additionalInstruction => [None..1]
             MedicationRequest.dosageInstruction:element.timing.repeat.bounds[x] => [None..None]
             MedicationRequest.dosageInstruction:element.timing.repeat.bounds[x]:boundsPeriod => [0..1]
             MedicationRequest.dosageInstruction:element.timing.repeat.bounds[x]:boundsPeriod.start => [None..None]
             MedicationRequest.dosageInstruction:element.timing.repeat.bounds[x]:boundsPeriod.end => [None..None]
             MedicationRequest.dosageInstruction:element.timing.repeat.offset => [None..None]
             MedicationRequest.dosageInstruction:element.site => [None..None]
             MedicationRequest.dosageInstruction:element.route => [None..None]
             MedicationRequest.dosageInstruction:element.method => [None..None]
             MedicationRequest.dosageInstruction:posology => [0..*]
             MedicationRequest.dosageInstruction:posology.id => [1..None]
             MedicationRequest.substitution => [None..None]
         }

     }
     package extension #paleturquoise {

     OncoFAIRCarePlan -[#black,dashed,thickness=2]-> OncoFAIRCPTreatment
     OncoFAIRCarePlan -[#black,dashed,thickness=2]-> OncoFAIRPharmacistAdvice
     OncoFAIRMedication -[#black,dashed,thickness=2]-> OncoFAIRMedicationType
     OncoFAIRMedicationAdministrationElement -[#black,dashed,thickness=2]-> OncoFAIRMAElementUrgent
     OncoFAIRMedicationAdministrationElement -[#black,dashed,thickness=2]-> OncoFAIRMAElementExpirationDate
     OncoFAIRMedicationAdministrationElement -[#black,dashed,thickness=2]-> OncoFAIRMAElementTraceability
     OncoFAIRMedicationAdministrationElement -[#black,dashed,thickness=2]-> OncoFAIRMAElementPlannedPeriod
     OncoFAIRMedicationRequestPrescription -[#black,dashed,thickness=2]-> OncoFAIRMRPrescriptionValidationDate
     OncoFAIRMedicationRequestComponent -[#black,dashed,thickness=2]-> OncoFAIRMRComponentExoneratingALD
     OncoFAIRMedicationRequestComponent -[#black,dashed,thickness=2]-> OncoFAIRMRComponentSolute
     OncoFAIRMedicationRequestElement -[#black,dashed,thickness=2]-> OncoFAIRElementForm
     OncoFAIRMedicationRequestElement -[#black,dashed,thickness=2]-> OncoFAIRMRElementSupply
     OncoFAIRMedicationRequestElement -[#black,dashed,thickness=2]-> OncoFAIRMRElementRank
     OncoFAIRMedicationRequestElement -[#black,dashed,thickness=2]-> OncoFAIRMRElementGoNogo
     OncoFAIRMedicationRequestElement -[#black,dashed,thickness=2]-> OncoFAIRPharmacistAdvice
     OncoFAIRMedicationRequestElement -[#black,dashed,thickness=2]-> OncoFAIRMRElementLinkType
     OncoFAIRMedicationRequestElement -[#black,dashed,thickness=2]-> OncoFAIRMRIdLinkedItem

        class OncoFAIRCPTreatment{

          Extension.extension => [1..None]
          Extension.extension:treatmentRank => [0..1]
          Extension.extension:treatmentRank.extension => [None..0]
          Extension.extension:treatmentRank.url => [None..None]
          Extension.extension:treatmentRank.value[x] => [None..None]
          Extension.extension:dayRank => [0..1]
          Extension.extension:dayRank.extension => [None..0]
          Extension.extension:dayRank.url => [None..None]
          Extension.extension:dayRank.value[x] => [None..None]
          Extension.extension:dateTimeReference => [1..1]
          Extension.extension:dateTimeReference.extension => [None..0]
          Extension.extension:dateTimeReference.url => [None..None]
          Extension.extension:dateTimeReference.value[x] => [None..None]
          Extension.url => [None..None]
          Extension.value[x] => [None..0]
        } 
        class OncoFAIRElementForm{

          Extension.extension => [None..0]
          Extension.url => [None..None]
          Extension.value[x] => [None..None]
        } 
        class OncoFAIRMAElementExpirationDate{

          Extension.extension => [None..0]
          Extension.url => [None..None]
          Extension.value[x] => [None..None]
        } 
        class OncoFAIRMAElementPlannedPeriod{

          Extension.extension => [None..0]
          Extension.url => [None..None]
          Extension.value[x] => [None..None]
          Extension.value[x].start => [1..None]
          Extension.value[x].end => [None..None]
        } 
        class OncoFAIRMAElementTraceability{

          Extension.extension:batchNumber => [0..1]
          Extension.extension:batchNumber.extension => [None..0]
          Extension.extension:batchNumber.url => [None..None]
          Extension.extension:batchNumber.value[x] => [None..None]
          Extension.extension:serialNumber => [0..1]
          Extension.extension:serialNumber.extension => [None..0]
          Extension.extension:serialNumber.url => [None..None]
          Extension.extension:serialNumber.value[x] => [None..None]
          Extension.url => [None..None]
          Extension.value[x] => [None..0]
        } 
        class OncoFAIRMAElementUrgent{

          Extension.extension => [None..0]
          Extension.url => [None..None]
          Extension.value[x] => [None..None]
        } 
        class OncoFAIRMedicationType{

          Extension.extension => [None..0]
          Extension.url => [None..None]
          Extension.value[x] => [None..None]
        } 
        class OncoFAIRMRComponentExoneratingALD{

          Extension.extension => [None..0]
          Extension.url => [None..None]
          Extension.value[x] => [None..None]
        } 
        class OncoFAIRMRComponentSolute{

          Extension.extension => [None..0]
          Extension.url => [None..None]
          Extension.value[x] => [None..None]
        } 
        class OncoFAIRMRElementGoNogo{

          Extension.extension:GoNogoStatus => [0..1]
          Extension.extension:GoNogoStatus.extension => [None..0]
          Extension.extension:GoNogoStatus.url => [None..None]
          Extension.extension:GoNogoStatus.value[x] => [None..None]
          Extension.extension:GoNogoReasonWaiting => [0..1]
          Extension.extension:GoNogoReasonWaiting.extension => [None..0]
          Extension.extension:GoNogoReasonWaiting.url => [None..None]
          Extension.extension:GoNogoReasonWaiting.value[x] => [None..None]
          Extension.url => [None..None]
          Extension.value[x] => [None..0]
        } 
        class OncoFAIRMRElementLinkType{

          Extension.extension => [None..0]
          Extension.url => [None..None]
          Extension.value[x] => [None..None]
        } 
        class OncoFAIRMRElementRank{

          Extension.extension => [None..0]
          Extension.url => [None..None]
          Extension.value[x] => [None..None]
        } 
        class OncoFAIRMRElementSupply{

          Extension.extension => [None..0]
          Extension.url => [None..None]
          Extension.value[x] => [None..None]
        } 
        class OncoFAIRMRIdLinkedItem{

          Extension.extension => [None..0]
          Extension.url => [None..None]
          Extension.value[x] => [None..None]
        } 
        class OncoFAIRMRPrescriptionValidationDate{

          Extension.extension => [None..0]
          Extension.url => [None..None]
          Extension.value[x] => [None..None]
        } 
        class OncoFAIRPharmacistAdvice{

          Extension.extension:pharmacistValidation => [0..1]
          Extension.extension:pharmacistValidation.extension => [None..0]
          Extension.extension:pharmacistValidation.url => [None..None]
          Extension.extension:pharmacistValidation.value[x] => [None..None]
          Extension.extension:pharmacistProposal => [0..1]
          Extension.extension:pharmacistProposal.extension => [None..0]
          Extension.extension:pharmacistProposal.url => [None..None]
          Extension.extension:pharmacistProposal.value[x] => [None..None]
          Extension.url => [None..None]
          Extension.value[x] => [None..0]
         }
     }
     package valueset #PaleVioletRed{
       }

package "Ressources de base" #palegreen {

 class "CarePlan" as  classc1c8e4b50c739ddc150dd233aa035d7a 

    classc1c8e4b50c739ddc150dd233aa035d7a --> OncoFAIRCarePlan

 class "Encounter" as  classd1e9f9f891de8f9a655739a01fbf68f0 

    classd1e9f9f891de8f9a655739a01fbf68f0 --> OncoFAIREncounter

 class "Medication" as  class353bd6f65060d17097c3b03141e79cce 

    class353bd6f65060d17097c3b03141e79cce --> OncoFAIRMedication

 class "MedicationAdministration" as  classcb08d1580a4f19d9fc3a0c98169f1144 

    classcb08d1580a4f19d9fc3a0c98169f1144 --> OncoFAIRMedicationAdministrationComponent

 class "MedicationAdministration" as  classcb08d1580a4f19d9fc3a0c98169f1144 

    classcb08d1580a4f19d9fc3a0c98169f1144 --> OncoFAIRMedicationAdministrationElement

 class "MedicationAdministration" as  classcb08d1580a4f19d9fc3a0c98169f1144 

    classcb08d1580a4f19d9fc3a0c98169f1144 --> OncoFAIRMedicationAdministrationReport

 class "MedicationRequest" as  class2071abb7e1482ea8731af3cdcaed7225 

    class2071abb7e1482ea8731af3cdcaed7225 --> OncoFAIRMedicationRequestPrescription

 class "Observation" as  classc680d437163cc6bab4f9bdb35c3073d0 

    classc680d437163cc6bab4f9bdb35c3073d0 --> OncoFAIRObservation

 class "Patient" as  class01122a97dca927210827560cb7d76af8 

    class01122a97dca927210827560cb7d76af8 --> OncoFAIRPatient

 class "MedicationRequest" as  class2071abb7e1482ea8731af3cdcaed7225 

    class2071abb7e1482ea8731af3cdcaed7225 --> OncoFAIRMedicationRequestComponent

 class "MedicationRequest" as  class2071abb7e1482ea8731af3cdcaed7225 

    class2071abb7e1482ea8731af3cdcaed7225 --> OncoFAIRMedicationRequestElement
}
@enduml